# Generated by Django 4.0.3 on 2022-03-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sector_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='setor',
            new_name='sector',
        ),
    ]
