# Generated by Django 4.0.3 on 2022-03-17 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Produto',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='Quantidade')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Venda',
            },
        ),
    ]
